### ISSUE TITLE
VM App Shared Image Galley JSON

### ISSUE THREAD

**Issue by Mtaddeo1010** [georgeollis/VM-Applications-Shared-Image-Gallery#1]
Where does the Policy JSON get import too?  The JSON looks to be ARM not policy definition?  When trying to save getting an error "The request content was invalid and could not be deserialized: 'Required property 'policyRule' expects a value but got null. Path 'properties', line 1, position 309.'."

**Comment by georgeollis** [comment]
You need to deploy it via the "Deploy a custom template" section within the Azure Portal.

**Comment by Mtaddeo1010** [comment]
Thank you.  I have deployed now via the custom template.  Any new VM coming online does not get the application installed automatically.  Manual remediation is all that is working.  Any ideas? And thank you.  This blog was excellent.

**Comment by Mtaddeo1010** [comment]
The issue is with when a VM is being created, the property Microsoft.Compute/virtualMachines/storageProfile.osDisk.osType is not present in the PUT request payload.  I noticed in the template when creating a new VM.  I had to remove the osType and add the below instead.  Thank you for this.  Was a great article and was very knowledgeable.  

{
                        "field": "Microsoft.Compute/imagePublisher",
                        "equals": "MicrosoftWindowsServer"
                    },
                    {
                        "field": "Microsoft.Compute/imageOffer",
                        "equals": "WindowsServer"
                    },

**Comment by Mtaddeo1010** [comment]
See above comment.  Thank you for everything.
